-- Provincias
INSERT INTO provinces (name) VALUES
  ('Pinar del Río'), ('Artemisa'), ('La Habana'), ('Mayabeque'),
  ('Matanzas'), ('Cienfuegos'), ('Villa Clara'), ('Sancti Spíritus'),
  ('Ciego de Ávila'), ('Camagüey'), ('Las Tunas'), ('Holguín'),
  ('Granma'), ('Santiago de Cuba'), ('Guantánamo'), ('Isla de la Juventud');

INSERT INTO municipalities (province_id, name) VALUES
  (1, 'Sandino'),
  (1, 'Mantua'),
  (1, 'Minas de Matahambre'),
  (1, 'Viñales'),
  (1, 'La Palma'),
  (1, 'Los Palacios')
  (1, 'Consolación del Sur'),
  (1, 'Pinar del Río'),
  (1, 'San Luis'),
  (1, 'San Juan y Martínez'),
  (1, 'Guane'),
  (2, 'Bahía Honda'),
  (2, 'Mariel'),
  (2, 'Guanajay'),
  (2, 'Caimito'),
  (2, 'Bauta'),
  (2, 'San Antonio de los Baños'),
  (2, 'Güira de Melena'),
  (2, 'Alquízar'),
  (2, 'Artemisa'),
  (2, 'Candelaria'),
  (2, 'San Cristobal'),
  (3, 'Plaza de la Revolución'), 
  (3, 'Centro Habana'), 
  (3, 'La Habana Vieja'),
  (3, 'Regla'), 
  (3, 'La Lisa'), 
  (3, 'Boyeros'), 
  (3, 'Cerro'),
  (3, 'Diez de Octubre'), 
  (3, 'Guanabacoa'), 
  (3, 'San Miguel del Padrón'),
  (3, 'Marianao'), 
  (3, 'Playa'), 
  (3, 'Cotorro'), 
  (3, 'Arroyo Naranjo'),
  (4, 'Bejucal'),
  (4, 'Santa Cruz del Norte'),
  (4, 'Jaruco'),
  (4, 'Madruga'),
  (4, 'Nueva Paz'),
  (4, 'San Nicolás'),
  (4, 'Güines'),
  (4, 'Melena del Sur'),
  (4, 'Batabanó'),
  (4, 'Quivicán'),
  (4, 'San José de las Lajas'),
  (5, 'Matanzas'), 
  (5, 'Cárdenas'), 
  (5, 'Varadero'), 
  (5, 'Ciénaga de Zapata'),
  (5, 'Jovellanos'), 
  (5, 'Colón'), 
  (5, 'Perico'), 
  (5, 'Pedro Betancourt'),
  (5, 'Martí'),
  (5, 'Limonar'),
  (5, 'Union de Reyes'),
  (5, 'Jagüey Grande'),
  (5, 'Calimete'),
  (5, 'Los Arabos'),
  (6, 'Aguada de Pasajeros'),
  (6, 'Rodas'),
  (6, 'Lajas'),
  (6, 'Cienfuegos'),
  (6, 'Palmira'),
  (6, 'Cumanayagua'),
  (6, 'Abreus'),
  (6, 'Santa Isabel de las Lajas'),
  (7, 'Corralillo'),
  (7, 'Quemado de Güines'),
  (7, 'Sagua la Grande'),
  (7, 'Encrucijada'),
  (7, 'Camajuaní'),
  (7, 'Caibarién'),
  (7, 'Remedios'),
  (7, 'Placetas'),
  (7, 'Santa Clara'),
  (7, 'Cifuentes'),
  (7, 'Santo Domingo'),
  (7, 'Ranchuelo'),
  (7, 'Manicaragua'),
  (8, 'Taguasco'),
  (8, 'Yaguajay'),
  (8, 'Jatibonico'),
  (8, 'Sancti Spíritus'),
  (8, 'Trinidad'),
  (8, 'Fomento'),
  (8, 'Cabaigúan'),
  (8, 'La Sierpe'),
  (9, 'Primero de Enero'),
  (9, 'Baraguá'),
  (9, 'Bolivia'), 
  (9, 'Chambas'),   
  (9, 'Ciego de Ávila'),
  (9, 'Ciro Redondo'),
  (9, 'Florencia'),
  (9, 'Majagua'),
  (9, 'Morón'),
  (9, 'Venezuela'),
  (10, 'Carlos Manuel de Céspedes'),
  (10, 'Esmeralda'),
  (10, 'Sierra de Cubitas'),
  (10, 'Minas'),
  (10, 'Nuevitas'),
  (10, 'Guáimaro'),
  (10, 'Sibanicú'),
  (10, 'Camagüey'),
  (10, 'Jimagüayú'),
  (10, 'Vertientes'),
  (10, 'Santa Cruz del Sur'),
  (10, 'Najasa'),
  (10, 'Céspedes'),
  (11, 'Ma natí'),
  (11, 'Puerto Padre'),
  (11, 'Jesús Menéndez'),
  (11, 'Majibacoa'),
  (11, 'Las Tunas'),
  (11, 'Jobabo'),
  (11, 'Colombia'),
  (11, 'Amancio'),
  (12, 'Gibara'),
  (12, 'Rafael Freyre'),
  (12, 'Banes'),
  (12, 'Antilla'),
  (12, 'Báguanos'),
  (12, 'Holguín'),
  (12, 'Calixto García'),
  (12, 'Cacocum'),
  (12, 'Urbano Noris'),
  (12, 'Cueto'),
  (12, 'Mayarí'),
  (12, 'Frank País'),
  (12, 'Sagua de Tánamo'),
  (12, 'Moa'),
  (13, 'Río Cauto'),
  (13, 'Cauto Cristo'),
  (13, 'Jiguaní'),
  (13, 'Bayamo'),
  (13, 'Yara'),
  (13, 'Manzanillo'),
  (13, 'Campechuela'),
  (13, 'Media Luna'),
  (13, 'Niquero'),
  (13, 'Pilón'),
  (13, 'Bartolomé Masó'),
  (13, 'Buey Arriba'),
  (13, 'Guisa'),
  (14, 'Contramaestre'),
  (14, 'Mella'),
  (14, 'San Luis'),
  (14, 'Segundo Frente'),
  (14, 'Songo-la Maya'),
  (14, 'Santiago de Cuba'),
  (14, 'Palma Soriano'),
  (14, 'Tercer Frente'),
  (14, 'Guamá'),
  (15, 'El Salvador'),
  (15, 'Manuel Tames'),
  (15, 'Yateras'),
  (15, 'Baracoa'),
  (15, 'Maisí'),
  (15, 'Imías'),
  (15, 'San Antonio del Sur'),
  (15, 'Caimanera'),
  (15, 'Guantánamo'),
  (15, 'Niceto Pérez'),
  (16, 'Municipio Especial Isla de la Juventud');

-- Marcas
INSERT INTO brands (name) VALUES
  ('Toyota'), ('Lada'), ('Hyundai'), ('Kia'), ('Mitsubishi'),
  ('Nissan'), ('Ford'), ('Chevrolet'), ('Honda'), ('Volkswagen'),
  ('BMW'), ('Mercedes-Benz'), ('Peugeot'), ('Fiat'), ('Mazda'),
  ('Suzuki'), ('Volvo'), ('GAZ'), ('Moskvich'), ('ZAZ');